<?php

/**
 * @file
 * OE Paragraphs module.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_entity_base_field_info().
 */
function oe_paragraphs_entity_base_field_info(EntityTypeInterface $entity_type): array {
  $fields = [];

  if ($entity_type->id() !== 'paragraph') {
    return $fields;
  }

  $fields['oe_paragraphs_variant'] = BaseFieldDefinition::create('string')
    ->setLabel(t('Variant'))
    ->setRequired(FALSE)
    ->setTranslatable(FALSE)
    ->setRevisionable(TRUE)
    ->setSetting('max_length', 255)
    ->setDisplayConfigurable('form', FALSE)
    ->setDisplayConfigurable('view', FALSE);

  return $fields;
}

/**
 * Implements hook_entity_type_alter().
 */
function oe_paragraphs_entity_type_alter(array &$entity_types) {
  // Make our field widget the default for paragraphs.
  /** @var \Drupal\Core\Entity\ContentEntityType $paragraph */
  $paragraph = $entity_types['paragraph'];
  $settings = $paragraph->get('default_reference_revision_settings');
  $settings['entity_form_display']['type'] = 'oe_paragraphs_variants';
  $paragraph->set('default_reference_revision_settings', $settings);
}
